---
title: "AusTraits - a curated trait database for the Australian flora"
output:
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: '4'
  html_document:
    keep_md: yes
    smart: no
    theme: yeti
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
editor_options:
  chunk_output_type: console
---

<script>
$(document).ready(function() {
  $items = $('div#TOC li');
  $items.each(function(idx) {
    num_ul = $(this).parentsUntil('#TOC').length;
    $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
  });

});
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Overview 

The AusTraits database is a compilation of measurements of plant traits for the Australian Flora. AusTraits synthesises data on 95 traits across more than 20,321 species, including  field campaigns, published literature, taxonomic monographs, and individual species descriptions. Traits vary in scope from physiological measures of performance (e.g. photosynthetic gas exchange, water-use efficiency) to morphological parameters (e.g. leaf area, seed mass, plant height) which link to aspects of ecological variation. AusTraits contains curated and harmonised individual- and species- level observations coupled to, where available, contextual information on site properties.


We envision AusTraits as an on-going collaborative resource that:

1. Increases our collective understanding the Australian flora; and
2. Facilitates accumulating and sharing of trait data;
3. Builds a sense of community among contributors and users; and
4. Aspires to fully transparent and reproducible research of highest standard.


To achieve these goals, AusTraits is built with the following objectives: 

* The workflow for harmonising different datasets is made fully open and reproducible;
* All data are shared under a standard open license permitting reuse;
* Contributions towards AusTraits are recognised via invitations to co-author data papers (i.e. releases of the data resource) and citation;
* Users of AusTraits are encouraged to both: provide adequate recognition via citation and also contribute towards the further development of the database.

## Why you should participate?

We are planning to submit a data paper describing the dataset to the journal “Scientific Data”, with all data contributors invited as co-authors. At that time, the dataset will be open access and we anticipate that paper to be widely cited. By participating you ensure your data remains available (via the Nature or Ecology (DRYAD) archives) into the future, thereby increasing the impact of your work.

## What is required from you?

Initially, all that is required from you is a response to this email confirming that you would like to contribute your dataset to Austraits. After receiving confirmation from data owners, we will be compiling a standard set of metadata and will ask you to answer some questions about your data. Our data processors will shoulder the majority of the workload and we do not anticipate the process requiring more than an hour or two of work on your part.

Ideally, what we'd like from you is as follows:

* Each dataset to correspond with a single primary source (eg paper, draft paper, thesis, report, flora, or other). If you have data that comes from multiple sources we would ideally separate in into multiple datasets.
* Each dataset has a single table of trait data, with different traits as columns and individuals as rows. Please also include species-name and site-name as columns this sheet. 
* Send us a copy of any documents (e.g. published paper, thesis or word doc) with details on units, replicates, site locations, who collected the data, and methods describing how the trait was measured.
* We ask that you make as few modifications to the data as you can to get it into the desired format. Our workflow will update trait names, units, and so forth.

After we have imported your data, we'll generate a report on your data and send it to you to review, as well as a copy of the draft paper.



.
