---
title: Overview of AusTraits workflow
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of AusTraits workflow}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  results = "asis",
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

library(austraits.build)

my_kable_styling <- util_kable_styling_html
```

AusTraits is an open-source, harmonised database of Australian plant trait data. Traits vary in scope, including morphological attributes (e.g. leaf area, seed mass, plant height), physiological measures of performance (e.g. photosynthetic gas exchange, water-use efficiency), tissue biochemical composition (e.g. leaf nitrogen content, leaf chlorophyll content), and life history traits (e.g. seed bank location, plant growth form, salinity tolerance).

This vignette provides an overview of our workflow, to demonstrate our commitment to creating a reliable, reproducible resource for anyone interested in plant traits. 

## AusTraits workflow 

### Data sources

The data in AusTraits is derived from nearly 300 distinct sources, each contributed by an individual researcher, government entity (e.g. herbaria), or NGO. Each reflects the research agenda of the individual/organisation who contributed the data - the species selected, traits measured, manipulative treatments performed, and locations sampled encompass the diversity of research interests present in Australia throughout past decades. To attain data, the AusTraits data curators have reached out to as many researchers as time permitted. This was done without explicitly soliciting datasets with specific traits; therefore, the spotty data coverage by trait or location simply represents what has been merged into AusTraits at this time.   

These datasets use different variable trait names, units and methods and have different data structures. 

### Standardising and harmonising data

To create a single database for distribution to the research community, we developed a reproducible and transparent workflow in R for merging each dataset into AusTraits. The pipeline ensures the following information is standardised across all datasets in AusTraits. A `metadata` file for each study documents how the `data tables` submitted by an individual contributor are translated into the standardised terms used in the AusTraits database. 

* **taxonomic nomenclature** follows the Australian Plant Census (APC), with a pipeline to update outdated taxonomy, correct minor spelling mistakes, and align with a known genus when a full species names isn't provided.  
* **trait names** are defined in our `traits.yml` file and only data for traits included in this file can be merged into AusTraits. The trait names used in the incoming dataset are mapped onto the appropriate AusTraits trait name. 
* For **numeric traits** the `traits.yml` file includes `units` and the allowable `range` of values. All incoming data are converted to the appropriate units and data outside the range of allowable values are removed from the main AusTraits data table.
* For **categorical traits** the `traits.yml` file includes a list of allowable `values`, allowed terms for the trait. Each categorical trait value is defined in the `traits.yml` file. Lists of substitutions translate the exact syntax and terms in a submitted dataset into the values allowed by AusTraits. This ensures that for a certain trait the same `value` has an identical meaning throughout the AusTraits database.
* Site locations are recorded in decimal degrees.

### Referencing sources and recording methods

The `metadata` file also includes all metadata associated with the study:

* The source information for each dataset is recorded. Most frequently, these are the primary publications derived from the dataset. 
* People associated with the collection of the data are listed, including their role in the project.
* Collection methods are included.
* Fields capture value type (mean, min, max, mode, range, bin) and associated replicate numbers, basis of value (measurement, expert_score, model_derived), entity type (species, population, individual), life stage (adult, juvenile,sapling, seedling), basis of record (field, field_experiment, preserved_specimen, captive_cultivated, lab, literature), and any additional measurement remarks. 
* Available data on location properties are recorded. 
* Available data on plot and treatment contextual properties are recorded.
* A context field, temporal_id, indicates if repeat measures were made on the same individual over time.
* A context field, method_id, indicates if the same trait was measured using multiple methods.
* Collection date is recorded.

### Error checking

* The AusTraits data curator runs a series of **tests** on each data set, detailed in the [adding data vignette](http://traitecoevo.github.io/austraits.build/articles/adding_data.html)
* These tests identify **misaligned units**, **unrecognised taxon names**, and **unsupported categorical trait values**
* These tests also identify and eliminate *most* **duplicate data** - instances where the same numeric trait data is submitted by multiple people
* Each dataset is then compiled into a **report** which summarises metadata and plots/charts trait values in comparison to other measurements of that trait in AusTraits. The report is reviewed by the data contributor to ensure metadata is complete and data values are as expected.
* A second member of the AusTraits team double checks each dataset before it is merged into the main repository.


## Detailed vignettes
A series of more detailed vignettes delve into specific aspects in greater detail:  

* **[austraits.build repo file structure](http://traitecoevo.github.io/austraits.build/articles/austraits_file_structure.html)**  
* **[austraits.build database structure](http://traitecoevo.github.io/austraits.build/articles/austraits_database_structure.html)**  
* **[how to build AusTraits](http://traitecoevo.github.io/austraits.build/articles/austraits.build.html)**  
* **[AusTraits definitions file](http://traitecoevo.github.io/austraits.build/articles/trait_definitions.html)**  
  
* **[how to contribute datasets to AusTraits](http://traitecoevo.github.io/austraits.build/articles/contributing_data.html)**  
* **[protocol for adding new datasets to AusTraits](http://traitecoevo.github.io/austraits.build/articles/adding_data.html)**  
