---
title: Contributing data to AusTraits
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contributing data to AusTraits}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  results = "asis",
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

library(austraits.build)
library(dplyr)
library(readr)

# root.dir <- rprojroot::find_root("remake.yml")
# knitr::opts_knit$set(root.dir = root.dir)

my_kable_styling <- my_kable_styling_html
```

AusTraits is an open-source harmonised database of Australian plant trait data. It exists because hundreds of researchers across Australia (and beyond) have contributed their datasets to this endeavour. Each dataset we receive incrementally broadens trait coverage for the Australian flora and, in turn, makes the database a little better to address your research questions. 

As such, we welcome all data contributions to AusTraits, including recently collected trait data, legacy trait data from your file archives, transcribed reference works, and transcribed datasets from the literature.

The AusTraits data-entry people then merge each dataset into AusTraits. AusTraits is a harmonised database: for each study we carefully check to ensure units are accurate, continuous trait values map in the expected range, categorical trait values map onto sensible terms, location data is accurate, taxon names are aligned to current standards, and all metadata are recorded. 

After completing a series of quality checks, we will send you a report to review that summarises the data and metadata. The reports include plots for each continuous trait, comparing values in your submission to those already in AusTraits. It plots your study sites on a map. It summarises your metadata and indicates the taxonomic alignments made. The report includes both targeted questions (sometimes) and automated questions, acting as prompts to review aspects of the report. Reviewing your report should not take long, and confirms the transparent, thorough process used to add data to AusTraits.

As a first step, all we really require is a **Data Spreadsheet** and a copy of your **Manuscript**. 


## Data

**Your dataset, preferably in a spreadsheet format.**

•	**Traits:** Make sure the trait names used in your dataset are easy to interpret or, alternatively, provide a brief definition

•	**Units:** Please make sure the units for each trait are provided as part of the trait name or in a separate spreadsheet/worksheet

•	**Value type:** We prefer to incorporate raw values (or individual means) in AusTraits, but can use site or multi-site means if that is what is available. For mean values, please provide sample size.

•	**Site:** For field studies, please provide site details (see more below).

•	**Context:** Optional, but AusTraits can read in one (or more) column(s) with contextual information, such as canopy position, experimental manipulation, dry vs. wet season, etc.

•	**Date:** Optional, but AusTraits can read in a column with sampling date (in any format)

•	**Species/taxa:** Please provide complete species names or a look-up table to match species codes. Out-dated taxonomy is fine – we have name-matching algorithms.


## Metadata 

The AusTraits structure has fields to input all metadata associated with your study, including methods, site details, and context. In detail:

•	**Methods:** For published studies the necessary methods and study information can be extracted from a publication; just attach a copy of the manuscript or the DOI. 

  -	The only commonly missing information is the general sampling period, such as ‘October-December 2020’
  
  -	For unpublished studies, provide brief methods for how each trait was measured; you can simply refer to a standard published protocol

•	**Study sites:** Whenever possible, AusTraits includes site names, site coordinates (latitude/longitude), and any other site details you have (vegetation description, soil chemistry, climate data, etc.). This information can be provided as a second spreadsheet or as additional columns in the main data spreadsheet. Just make sure the site name is the same in both spreadsheets.

•	**Context:** If your study includes contextual variables, make sure the context values are included as columns in the data spreadsheet. Also, please make sure the contextual values are self-explanatory or provide the necessary explanation.

•	**Authors:** Authorship is extended to anyone who played a key intellectual role in the experimental design and data collection. Most studies have 1-3 authors. For each author, please provide a **name**, **institutional affiliation**, **email address**, and their **role** in the study (collector – central role in the collection of data; lab_leader – students/postdocs will often include their supervisor or another head-of-lab who was integrally involved in the design of the field study or data collection.) (Additional field assistants can be listed under acknowledgements.)

•	**Source:** The published manuscript is generally the source. If different traits or observations from a single dataset were published separately, please provide both references.


## Most common hang-ups

•	**Categorical trait values:** If you have categorical traits, please define any trait values (i.e. entries for that trait) that are not self-explanatory. A copy of our trait_definitions file, including allowable values for each trait is available [here](http://traitecoevo.github.io/austraits.build/articles/Trait_definitions.html). The trait_definitions file is a work-in-progress and additional trait values can be added if needed to capture the exact meaning you intended.

•	**Data sourced from others:** For numerical traits, AusTraits strives to only include data collected by you for this project, to avoid having multiple entries of the same measurement/observation. If you have certain trait values that were sourced from the literature, an online database, or colleagues, please indicate that clearly. If trait values for some species were collected by you and others were sourced, it is very helpful if you could add a column to your spreadsheet that indicates the source for different rows of data.
