---
title: "Overview of data in `Austraits` compilation"
author: "Daniel Falster, Rachael Gallagher, Dony Indiarto, Sam Andrew, James Lawson, Lizzy Wenk"
output:
  html_document:
    df_print: kable
    highlight: tango
    keep_md: no
    smart: no
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options:
  chunk_output_type: console
# date: "`r Sys.Date()`"
# output: rmarkdown::html_vignette
# vignette: >
#  %\VignetteIndexEntry{austraits}
#  %\VignetteEngine{knitr::rmarkdown}
#  %\VignetteEncoding{UTF-8}
---


<!-- hack to get indentation on 3rd level of floating TOC; see
https://stackoverflow.com/questions/46201753/rmarkdown-indentation-of-toc-items-in-html-output
 -->
<script>
$(document).ready(function() {
  $items = $('div#TOC li');
  $items.each(function(idx) {
    num_ul = $(this).parentsUntil('#TOC').length;
    $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
  });

});
</script>

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
# knitr defaults
root.dir = rprojroot::find_root("remake.yml")
knitr::opts_knit$set(root.dir = root.dir)
knitr::opts_chunk$set(echo=FALSE, cache=FALSE)
# default for table format
options(knitr.table.format = "html")

# Guidelines for writing report code
# - use tidyverse style and format: http://htmlpreview.github.io/?https://github.com/nicercode/2018_BEES_regression/blob/master/tidyverse.html
# - use kableExtra for styling: https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html
# - use knitr chunck options: https://rmarkdown.rstudio.com/lesson-3.html

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
library(knitr)
library(dplyr)
library(leaflet)
library(ggbeeswarm)
library(kableExtra)

source("R/austraits.R")
source("R/support.R")
source("R/report_utils.R")
source("R/report_notetaker.R")

## Assumes to items exist in global name space
if(!exists("austraits")) {
  austraits <- remake::make("austraits")
  # stop("austraits must exist in global name space to knit a report")
}

definitions <- austraits$definitions
knitr::opts_chunk$set(fig.cap='', fig.path = file.path(root.dir,"vignettes/figures", paste0("austraits","_")))
```

# Dataset structure and definitions

The `Austraits` dataset has `r length(austraits)` components:
```{r}
names(austraits)
````


# Coverage

# Traits 1

# Traits 2
