---
title: "Metadata documents for austraits"
output: github_document
---


##  Taxonomy


Species lists align 

- APC_name/ ID as unknown when hasn't been checked
NA means has been checked and is indetermined



# # Add APC and APNI names / handles
# # Add Native / introduced / naturalised

# # metadata
# taxon = Accepted name of species in The Plant List 
# TPL_ID = Record ID of the taxon in The Plant List 
# family = Family of taxon (extracted from The Plant List) 
# authority = author of taxon (extracted from The Plant List)
# status = Taxonomic status of taxon in The Plant List
# APC_name = Accepted name of species in the Australian Plant Census
# APC_ID = Record ID of the taxon in the Australian Plant Census -- https://biodiversity.org.au/nsl/services/node/apc/2908862
# APNI_ID = Record ID of the taxon in the Australian Plant Name Index -- http://id.biodiversity.org.au/node/apni/2899106

# # Usage
# TPL_ID -> http://www.theplantlist.org/tpl1.1/record/kew-450649

# # Taxonstand docs: https://www.rdocumentation.org/packages/Taxonstand/versions/2.1/topics/TPL
https://cran.r-project.org/web/packages/Taxonstand/index.html
# ALA: use the https://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2899106



# Reports

Reports are written in [Rmarkdown](https://rstudio.github.io/rmarkdown/) and generated via the [knitr](https://cran.r-project.org/web/packages/knitr/) package. Several types of report are avaiable. Templates are stored in the folder `reports`. 

Guidelines for writing report code

- use knitr chunck options: https://rmarkdown.rstudio.com/lesson-3.html
- use tidyverse style and format: http://htmlpreview.github.io/?https://github.com/nicercode/2018_BEES_regression/blob/master/tidyverse.html
- use kableExtra for styling: https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

## Austraits report

## Sudy report

## Sofwtare

### ggmap

We use the package [ggmap](https://github.com/dkahle/ggmap/) to generate maps based on the XXXXstatenmapXXX databse(?). Because of an [known issue in ggmap](https://github.com/dkahle/ggmap/issues/203), you may need to install the dveelopment version of ggamp (at least until the fix becomes availabel on cran.

```
devtools::install_github("dkahle/ggmap")
```

The plotting command also make use of the package [ggrepel](https://cran.r-project.org/web/packages/ggrepel/index.html).

Code for generating maps is available in the file `R/report_maps.R`. 

## Future approaches to consider:

- For maps, could use [leaflet](https://rstudio.github.io/leaflet/) package, though I think this still needs substantial amount of downloading
