# This file is automatically generated from traits.build
# package, via the file remake.yml.whisker:
# edit the file there (or the files that it includes).

# Load R resources
library(traits.build)

# Load data resources
schema <- get_schema()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

# Build each source
Test_2022_config <- dataset_configure("data/Test_2022/metadata.yml", definitions)
Test_2022_raw <- dataset_process("data/Test_2022/data.csv", Test_2022_config, schema, resource_metadata, unit_conversions)
Test_2022 <- build_update_taxonomy(Test_2022_raw, taxon_list)


austraits_raw <- build_combine(
        Test_2022,
        NULL)

# Version information
version_number <- util_get_version("config/metadata.yml")
git_SHA <- util_get_SHA()

# Combine all the source into one resource
austraits <- build_add_version(austraits_raw, version_number, git_SHA)

# Save to file
dir.create("export/data/curr", FALSE, TRUE)
saveRDS(austraits, "export/data/curr/austraits.rds")
