metadata:
  resource_type: dataset
  title: 'AusTraits: a curated plant trait database for the Australian flora'
  version: v4.0
  doi: 10.5281/zenodo.5112001
  structure_URI: https://github.com/traitecoevo/austraits.build
  publisher: Zenodo
  geo_location:
    geo_location_place: Australia
    geodetic_datum: EPSG:4326
  language: eng
  related_identifiers:
  - related_identifier_type: url 
    identifier: https://github.com/traitecoevo/austraits.build/tree/v3.0.2
    relation_type: isCompiledBy
    resource_type: dataset
  - related_identifier_type: doi
    identifier: 10.1038/s41597-021-01006-6
    relation_type: isCitedBy
    resource_type: publication-article
  references: "Falster, Gallagher et al (2021) *AusTraits, a curated plant trait database for the Australian flora*. Scientific Data 8: 254, https://doi.org/10.1038/s41597-021-01006-6"
  license:
    rights: CC-BY-4.0    
    rights_holder: Falster, Daniel
    rights_URI: https://creativecommons.org/licenses/by/4.0/
    description: Under this license, the material can be copied and redistributed in any medium or format. It can be remixed, transformed, and built upon for any purpose, even commercially. Re-users must give appropriate credit, provide a link to the license, and indicate if changes were made. Re-users may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
  subject:
    subject_scheme: ANZSRC Field of Research
    scheme_URI: https://linked.data.gov.au/def/anzsrc-for/2020/
    value_URI:
    - https://linked.data.gov.au/def/anzsrc-for/2020/3103
    - https://linked.data.gov.au/def/anzsrc-for/2020/3104
    - https://linked.data.gov.au/def/anzsrc-for/2020/4104
    - https://linked.data.gov.au/def/anzsrc-for/2020/300703
    - https://linked.data.gov.au/def/anzsrc-for/2020/060705
    - https://linked.data.gov.au/def/anzsrc-for/2020/050202
    - https://linked.data.gov.au/def/anzsrc-for/2020/060208
    - https://linked.data.gov.au/def/anzsrc-for/2020/069902
  funding_reference:
  - funder_name: ARDC
    award_IRI: doi.org/10.47486/DP720
    award_number: DP720
    award_title: AusTraits, A national database on the traits of Australia's complete flora.
  - funder_name: ARDC
    award_IRI: doi.org/10.47486/TD044
    award_number: TD044
    award_title: AusTraits, A national database on the traits of Australia's complete flora.
  - funder_name: ARC
    award_IRI:
    award_number: 
    award_title: 
  - funder_name: ARC
    award_IRI:
    award_number: 
    award_title: 
  - funder_name: ARC
    award_IRI:
    award_number: 
    award_title: 
  creators: 
  - last_name: Falster
    given_name: Daniel
    ORCID: 0000-0002-9814-092X
    affiliation: Evolution & Ecology Research Centre, UNSW Sydney, Australia
  - last_name: Elizabeth
    given_name: Wenk
    ORCID: 
    affiliation: Evolution & Ecology Research Centre, UNSW Sydney, 
  contributors: .na
