metadata:
    resource_type: dataset
    access_right_category: success
    doi: 10.5281/zenodo.5112001
    strcture_URI: https://github.com/traitecoevo/austraits.build
    version: v4.0
    creators: .na
    contributors: .na
    title: 'AusTraits: a curated plant trait database for the Australian flora'
    language: eng
    related_identifiers:
    - scheme: url 
      identifier: https://github.com/traitecoevo/austraits.build/tree/v3.0.2
      relation: isCompiledBy
      resource_type: dataset
    - scheme: doi
      identifier: 10.1038/s41597-021-01006-6
      relation: isCitedBy
      resource_type: publication-article
    access_right: open
    rights_holder: Falster, Daniel
    references: "Falster, Gallagher et al (2021) *AusTraits, a curated plant trait database for the Australian flora*. Scientific Data 8: 254, https://doi.org/10.1038/s41597-021-01006-6"
    publication_date: '2022-11-25'
    publisher: Zenodo
    license:
      id: CC-BY-4.0    
      rights_URI: https://creativecommons.org/licenses/by/4.0/
      description: Under this license, the material can be copied and redistributed in any medium or format. It can be remixed, transformed, and built upon for any purpose, even commercially. Re-users must give appropriate credit, provide a link to the license, and indicate if changes were made. Re-users may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
    subject:
      subject_scheme: ANZSRC Field of Research
      scheme_URI: https://linked.data.gov.au/def/anzsrc-for/2020/
      values_IRI:
      - https://linked.data.gov.au/def/anzsrc-for/2020/3103
      - https://linked.data.gov.au/def/anzsrc-for/2020/4104
      - https://linked.data.gov.au/def/anzsrc-for/2020/3104
      - https://linked.data.gov.au/def/anzsrc-for/2020/300703
      - https://linked.data.gov.au/def/anzsrc-for/2020/060705
      - https://linked.data.gov.au/def/anzsrc-for/2020/050202
      - https://linked.data.gov.au/def/anzsrc-for/2020/060208
      - https://linked.data.gov.au/def/anzsrc-for/2020/069902
    geo_location:
      geo_location_place: Australia
      geodetic_datum: EPSG:4326
    funding_reference:
    - funder_name: ARDC
      scheme: doi
      scheme_IRI: 10.47486/DP720
      award_number: DP720
      award_title: AusTraits, A national database on the traits of Australia's complete flora.
    - funder_name: ARDC
      scheme: doi
      scheme_IRI: 10.47486/TD044
      award_number: TD044
      award_title: AusTraits, A national database on the traits of Australia's complete flora.
    - funder_name: ARC
      scheme: doi
      scheme_IRI:
      award_number: 
      award_title: 
    - funder_name: ARC
      scheme: doi
      scheme_IRI:
      award_number: 
      award_title: 
    - funder_name: ARC
      scheme: doi
      scheme_IRI:
      award_number: 
      award_title: 
  links:
    doi: https://doi.org/10.5281/zenodo.5112001
    conceptdoi: https://doi.org/10.5281/zenodo.3568417
    bucket: https://zenodo.org/api/files/9c997956-8254-4fcc-a17b-5fe1fd079022
    conceptbadge: https://zenodo.org/badge/doi/10.5281/zenodo.3568417.svg
    html: https://zenodo.org/record/5112001
    latest_html: https://zenodo.org/record/5112001
    badge: https://zenodo.org/badge/doi/10.5281/zenodo.5112001.svg
    latest: https://zenodo.org/api/records/5112001
  
  
  