---
title: Contributing to `AusTraits`
author: Daniel Falster
date: "`r Sys.Date()`"
header-includes:
   - \usepackage{pmboxdraw}
output:
  github_document:
    toc: yes
    toc_depth: 4
  html_document:
    keep_md: yes
    smart: no
    theme: yeti
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  chunk_output_type: console
---

<!-- Contributing.md is generated from Contributing.Rmd Please edit that file -->

<!-- hack to get indentation on 3rd level of floating TOC in html; see
https://stackoverflow.com/questions/46201753/rmarkdown-indentation-of-toc-items-in-html-output
 -->
<script>
$(document).ready(function() {
  $items = $('div#TOC li');
  $items.each(function(idx) {
    num_ul = $(this).parentsUntil('#TOC').length;
    $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
  });

});
</script>

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
# knitr defaults
root.dir = rprojroot::find_root("remake.yml")
knitr::opts_knit$set(root.dir = root.dir)

knitr::opts_chunk$set(
  echo=FALSE, cache=FALSE, message=FALSE, warning=FALSE,
  results='asis',
  fig.cap='', 
  fig.path = file.path(root.dir,"docs/figures", paste0("contributing","_")),
  out.width = "100%"
)
```

Separate documents provide information on: 

- Overview of Austraits: [Falster et al 2020](XXXX)
- Accessing and using AusTraits: XXXX
- Building Austraits: [Building](Building.md)
- Contributing to AusTraits: [Contributing](Contributing.md)
- Working with GitHub repository: [Working_with_github](Working_with_github.md)
- Tips & Tricks for AusTraits developes: [TipsTricks](TipTricks.md)
- Full list of trait definitions: [Trait_definitions](Trait_definitions.md)

## Ways to contribute

AusTraits is a community resource and we are very keen for people to contribute. This docuemnet describes some of the ways you can contribute.

Here are some of the ways you can contribute: 

**Reporting Errors**: If you notice a possible error in AusTraits, please [post an issue on GitHub](https://github.com/traitecoevo/austraits.build/issues) . If you can, please provide code illustrating the problem.

**Refining documentation:** Data contributors and data users who are less familiar with the AusTraits format and code than the custodians may determine that important descriptions or steps are omitted from this documentation file. We welcome additions and edits that make using the existing data or adding new data easier for the community.

**Value adding / expanding existing data**: If you would like to value-add to AusTraits in some other way, please get in contact by [posting an issue](https://github.com/traitecoevo/austraits/issues) with an idea or offer of time.

**Contributing new data**: We gladly accept new data contributions to AusTraits. If you would like to contribute data, the requirements are:

- Data were collected for Australian plant species growing in Australia
- You collected data on one of the traits list in the [trait definitions table](Trait_definitions.md).
- You are willing to release the data under an open license for reuse by the scientific community.
- You make it is as easy as possible for us to incorporate your data by carefully following the instructions below.


For full instructions on preparing data for inclusion in AusTraits see the sections on formatting of raw data files for AusTraits in the document [Building Austraits](Building.md).

For instructions on working with github, see the document [Working with github](Working_with_github.md).


Please note that the austraits project is released with a [Contributor Code of Conduct](../.github/CODE_OF_CONDUCT.md). By contributing to this project you agree to abide by its terms.
